name: "[QE] Cypress Runner"

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:
    inputs:
      branch:
        description: "Choose another branch to test"
        required: true
        default: master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Check Chrome version
        run: chrome --version

      - name: Checkout Reviews and Ratings app
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Get cy-runner
        run: git clone https://github.com/vtex-apps/cy-runner.git

      - name: Cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Cypress
        run: yarn install --frozen-lockfile
        working-directory: ./cy-runner

      - name: Cypress Runner
        run: yarn cy-r
        env:
          VTEX_QE: ${{ secrets.VTEX_QE }}
          NODE_NO_WARNINGS: 1

      - name: Save results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: cy-runner-logs
          path: cy-runner/logs
