name: '[PRT] Quality Engineering'

on:
  pull_request_target:
    branches:
      - main
      - master
    types:
      - labeled

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v1.0.0
    with:
      danger: true
      dangerRequireChangelog: false
      nodeLint: true
      nodeTest: false
      reactTest: true
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_reviews-and-ratings-ts
      nodeSonarOrganization: vtex-apps
      dotnetLint: true
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_reviews-and-ratings-dotnet
      dotnetSonarOrganization: vtex-apps
      cypress: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
